const ingredients = [
  { id: 1, ingredientName: 'avokaado' },
  { id: 2, ingredientName: 'banaan' },
  { id: 3, ingredientName: 'basiilik/petersell' },
  { id: 4, ingredientName: 'hapukoor' },
  { id: 5, ingredientName: 'jahu' },
  { id: 6, ingredientName: 'juust' },
  { id: 7, ingredientName: 'kana' },
  { id: 8, ingredientName: 'kartul' },
  { id: 9, ingredientName: 'kodujuust' },
  { id: 10, ingredientName: 'kurk' },
  { id: 11, ingredientName: 'küüslauk' },
  { id: 12, ingredientName: 'lõhe' },
  { id: 13, ingredientName: 'majonees/ketšup' },
  { id: 14, ingredientName: 'muna' },
  { id: 15, ingredientName: 'murulauk' },
  { id: 16, ingredientName: 'õli' },
  { id: 17, ingredientName: 'piim' },
  { id: 18, ingredientName: 'porgand' },
  { id: 19, ingredientName: 'porru' },
  { id: 20, ingredientName: 'puljong' },
  { id: 21, ingredientName: 'redis' },
  { id: 22, ingredientName: 'riivsai' },
  { id: 23, ingredientName: 'sai' },
  { id: 24, ingredientName: 'sibul' },
  { id: 25, ingredientName: 'sinep' },
  { id: 26, ingredientName: 'suhkur' },
  { id: 27, ingredientName: 'sulajuust' },
  { id: 28, ingredientName: 'till' },
  { id: 29, ingredientName: 'toorjuust' },
  { id: 30, ingredientName: 'vahukoor' },
  { id: 31, ingredientName: 'viiner' },
  { id: 32, ingredientName: 'või' },
];

module.exports = ingredients;
