const toiduained = [
  { id: 1, Nimetus: 'avokaado' },
  { id: 2, Nimetus: 'banaan' },
  { id: 3, Nimetus: 'basiilik/petersell' },
  { id: 4, Nimetus: 'hapukoor' },
  { id: 5, Nimetus: 'jahu' },
  { id: 6, Nimetus: 'juust' },
  { id: 7, Nimetus: 'kana' },
  { id: 8, Nimetus: 'kartul' },
  { id: 9, Nimetus: 'kodujuust' },
  { id: 10, Nimetus: 'kurk' },
  { id: 11, Nimetus: 'küüslauk' },
  { id: 12, Nimetus: 'lõhe' },
  { id: 13, Nimetus: 'majonees/ketšup' },
  { id: 14, Nimetus: 'muna' },
  { id: 15, Nimetus: 'murulauk' },
  { id: 16, Nimetus: 'õli' },
  { id: 17, Nimetus: 'piim' },
  { id: 18, Nimetus: 'porgand' },
  { id: 19, Nimetus: 'porru' },
  { id: 20, Nimetus: 'puljong' },
  { id: 21, Nimetus: 'redis' },
  { id: 22, Nimetus: 'riivsai' },
  { id: 23, Nimetus: 'sai' },
  { id: 24, Nimetus: 'sibul' },
  { id: 25, Nimetus: 'sinep' },
  { id: 26, Nimetus: 'suhkur' },
  { id: 27, Nimetus: 'sulajuust' },
  { id: 28, Nimetus: 'till' },
  { id: 29, Nimetus: 'toorjuust' },
  { id: 30, Nimetus: 'vahukoor' },
  { id: 31, Nimetus: 'viiner' },
  { id: 32, Nimetus: 'või' },
];

module.exports = toiduained;
