const recipes = [
  {
    id: 1,
    recipeName: 'Mozzarella saiad',
    ingredientsList: [
      '8 viilu röstsaia',
      '2 muna',
      '1 mozzarellapall',
      'riivsaia',
      'soola',
    ],
    preparationMethod:
      'Lõika saial ära koored ning poolita saiad nii, et moodustuks kolmnurk. Viiluta mozzarella. Klopi lahti munad ja maitsesta soolaga. Vala taldrikule riivsai. Pane kahe kolmnurga vahele mozzarellat ning vajuta kahvliga ääred kokku. Kasta saiakolmnurk munasegusse ja seejärel riivsaia taldrikusse. Vala pannile küpsetamiseks mõeldud oliiviõli umbes sentimeetri jagu ning kuumuta keskmise kuumusega õli kuumaks. Prae saiakolmnurgad mõlemalt poolt kuldpruuniks. Serveeri kohe!',
    koostisosad: [6, 14, 22, 23],
    image: 'pildid/mozsai.jpg',
  },
  {
    id: 2,
    recipeName: 'Lõhesupp',
    ingredientsList: [
      '3 kartulit',
      '2 porgandit',
      '800 ml vett või puljongit',
      '200 ml vahukoort',
      '300-400 g lõhefileed',
      '80-100 g porrut',
      'sool ja pipar',
      'serveerimiseks sidruni- või laimilõike',
    ],
    preparationMethod:
      'Keeda vesi või puljong. Vala sisse köögiviljasegu ja porru ning lase keeda 10-15 minutit või kuni köögivili on pehme. Lisa vahukoor, puhasta lõhe nahast ja luudest ning tee neist 1,5 cm kuubikud. Lisa supile kala ja lase supp keema ning keera kuumus maha, sest kala küpseb kiiresti.',
    koostisosad: [8, 12, 18, 19, 30],
    image: 'pildid/lohesupp.jpg',
  },
  {
    id: 3,
    recipeName: 'Avokaado-kodujuustusalat',
    ingredientsList: [
      '1 avokaado',
      '3/4 kurki',
      '3-4 redist',
      '200 g kodujuustu',
      'soola ja pipart',
      'murulauku',
    ],
    preparationMethod:
      'Lõika avokaado pooleks, eemalda südamik ja koor, lõika kuubikuteks. Haki redised ja kurk väikesteks tükkideks. Sega kausis kõik koostisained, lisa hakitud murulauk. Maitsesta soola ja pipraga. Serveeri kohe. Sellest kogusest tuleb väike kauss salatit. Värske kurgi asemel võid kasutada ka värsket soolakurki. Avokaado saad pehmeks kui jätad selle paberkoti sees toatemperatuurile (paariks päevaks) seisma..',
    koostisosad: [1, 9, 10, 15, 21],
    image: 'pildid/avokaadosalat.jpg',
  },
  {
    id: 4,
    recipeName: 'Kartuli-porgandikotletid',
    ingredientsList: [
      '3-4 kartulit',
      '1 porgand',
      '1 muna',
      '4 + 4 spl jahu',
      '2 spl piima',
      '50 g riivitud juustu',
      'soola',
      'pipart',
      'peterselli',
      'rasvainet praadimiseks',
    ],
    preparationMethod:
      "Riivi kartulid jämeda riiviga. Riivi porgand peene riiviga. Klopi lahti muna, lisa 4 spl jahu ja piim, maitsesta soola-pipraga. Sega sisse juust ja kartulid-porgandid. Veereta ülejäänud jahus pallikesed ja suru lamedaks. Kuumuta pannil rasvaine. Pane kotletid pannile ja prae keskmisel kuumusel mõlemalt poolt pruuniks. Hoia kuumust keskmise peal, et kartul korralikult läbi küpseks. Serveeri koheselt. Raputa peale hakitud peterselli ja einesta hapukoorega. Krõbedateks kotlettideks kulub rasvainet üsna palju, mistõttu kasuta rasvainena ghii'd, see on kõhule sõbralikum!",
    koostisosad: [5, 6, 8, 14, 17, 18],
    image: 'pildid/porkotletid.jpg',
  },
  {
    id: 5,
    recipeName: 'Kartuli-kodujuustu pulgad',
    ingredientsList: [
      '5 keedukartulit',
      '2 muna,100 g riivsaia',
      '100 g kodujuustu',
      '2-3 spl nisujahupraadimiseks',
      'toiduõli',
      'maitsestamiseks pipart, koriandrit, soola, kurkumat',
    ],
    preparationMethod:
      'Riivi kartul, lisa munad, kodujuust, maitseained, sega korralikult. Lisa jahu, sega. Vormi pulgakesed, paneeri riivsaias ja prae õlis mõlemalt poolt kuldpruuniks. Serveeri värske salatiga või meelepärase kastmega.',
    koostisosad: [5, 8, 9, 14, 22],
    image: 'pildid/kartulipulgad.jpg',
  },
  {
    id: 6,
    recipeName: 'Ahjulõhe muna-juustu kattega',
    ingredientsList: [
      '700-800 g tükk lõhefileed',
      '250 g riivitud juustu',
      '2-3 munakollast',
      'tilli, soola ja valget pipart',
    ],
    preparationMethod:
      'Aseta lõhefilee ahjuplaadile, raputa peale soola ja pipart ning hakitud till. Klopi munakollased lahti, sega riivitud juustuga. Kata kala juustu-munaseguga. Küpsta 200-kraadises ahjus 20-30 minutit, kuni juust on sulanud ja kala omandanud kuldkollase värvuse. Serveeri maitsestatud riisiga või kuldsete ahjukartulitega. Kala kõrvale sobib külm kaste, mis on valmistatud hakitud tillist, värskest või marineeritud kurgist, mädarõikamaitselisest majoneesist, hapukoorest.',
    koostisosad: [6, 12, 14, 28],
    image: 'pildid/ahjulohe.jpg',
  },
  {
    id: 7,
    recipeName: 'Õhukesed pannkoogid ehk krepid',
    ingredientsList: [
      '4 muna',
      '60 g suhkrut',
      '200 g nisujahu',
      'näpuotsaga soola',
      '5 dl piima',
      '50 g sulatatud võid',
    ],
    preparationMethod:
      'Klopi munad suhkruga lahti, sega juurde jahu, piim ja näpuotsaga soola ning sega ühtlaseks. Viimasena lisa juurde sulavõi, sega läbi.  Kuumuta suur pann, lisa sobiv kogus tainast* ja küpseta paar minutit keskmisel kuumusel, kuni pannkook on altpoolt kaunilt kuldne. Keera ringi ja küpseta ka teiselt poolt. Nipid ja soovitused: Eriti mugav on kasutada spetsiaalset pannkoogipanni. Meie tõstame suure kulbitäie tainast ühte panni serva, siis keerame-kallutame panni, nii et tainas valguks ühtlase õhukese kihina laiali. Tulemuseks on hästi ilusad ümmargused pannkoogid.',
    koostisosad: [5, 14, 17, 32],
    image: 'pildid/krepid.jpg',
  },
  {
    id: 8,
    recipeName: 'Banaanipannkoogid',
    ingredientsList: [
      '2 tumedaks läinud pehmet banaani',
      '2 muna',
      '2 spl jahu',
      '75 g hapukoort',
      '3 tl suhkrut',
      '1 tl vanillisuhkrut',
      'näpuotsatäis kardemoni',
    ],
    preparationMethod:
      'Vajuta banaanid kahvliga katki. Kui tahad veidi paksemaid pannkooke, siis purusta vähem ning kui õhemaid, siis rohkem. Lisa munad, hapukoor, suhkur ja vanillisuhkur, sega. Seejärel lisa jahu ning sega veelkord korralikult. Prae pannil pisikesed pannkoogid.',
    koostisosad: [2, 4, 5, 14],
    image: 'pildid/banaanikook.jpg',
  },
  {
    id: 9,
    recipeName: 'Krutskiga viineripirukad',
    ingredientsList: [
      '10 viilu röstsaia',
      '10 pikka viinerit',
      '5 sl majoneesi või ketšupit',
      '1 sl sinepit',
      '100 g riivjuustu',
    ],
    preparationMethod:
      'Rulli saiaviilud tainarulli abil veidi õhemaks ja lapikumaks. Sega ketšup või majonees sinepiga, määri teelusikatäis segu saiaviilule. Aseta viiner ristipidi ühte nurka ning keera sai ümber viineri rulli. Aseta ahjuvormi, liitekoht all. Puista peale riivitud juust. Küpseta 200-kraadises ahjus umbes 10-15 minutit, kuni viiner on läbi küpsenud ja juust sulanud.',
    koostisosad: [6, 13, 23, 25, 31],
    image: 'pildid/viineripirukas.jpg',
  },
  {
    id: 10,
    recipeName: 'Kanakaste sulatatud juustuga',
    ingredientsList: [
      '2 suuremat kanafileed',
      '200 g sulatatud juustu',
      '2 dl vahukoort',
      'hakitud basiilikut või peterselli',
      'praadimiseks õli',
    ],
    preparationMethod:
      'Lõika kanafileed väikesteks tükkideks, maitsesta kergelt soola-pipraga ning pruunista mõõdukalt tugeval kuumusel pannil õlis (kui pann on väiksem, võid teha seda jaokaupa). Lisa rõõsk koor, hauta umbes 5 minutit, kuni kanatükid on küpsed. Lisa sulatatud juust ja kuumuta tasasel tulel, kuni juust on sulanud. Hauta rooga veel 5 minutit, siis maitsesta värskete ürtidega. Serveeri riisi, makaronide või keedetud kartulitega.',
    koostisosad: [3, 7, 27, 30],
    image: 'pildid/kanakastejuustuga.jpg',
  },
  {
    id: 11,
    recipeName: 'Krõbedad kanapalad tillikastmega',
    ingredientsList: [
      '2 kanafileed',
      'paar näpuotsatäit soola',
      '6 supilusikatäit hapukoort',
      '4 suurt peotäit riivsaia',
    ],
    preparationMethod:
      'Lõika kanafileed väiksemateks tükkideks ja maitsesta need soolaga Pane hapukoor kaussi ning kasta kanatükid selle sisse. Aseta teise kaussi riivsai ning pista ükshaaval kanatükid sellesse (jälgi, et kanatükid saaksid riivsaiaga ilusti kaetud). Aseta kanaribad ahjurestile (nii küpsevad need mõlemalt poolt krõbedaks) või -plaadile ning küpseta 200 kraadi juures 20-25 minutit.  Kastme valmistamiseks sega hapukoor ja till omavahel ja serveeri koos kanapaladega.',
    koostisosad: [4, 7, 22, 28],
    image: 'pildid/kanapulgad.jpg',
  },
  {
    id: 12,
    recipeName: 'Porgandi-munavõie',
    ingredientsList: [
      '4 keedetud muna',
      '75 g toorjuustu',
      '0,5 keedetud porgandit',
      '120 g kodujuust',
      'soola, pipart',
      'röstsai',
    ],
    preparationMethod:
      'Eralda munakollased ning vahusta need mikseriga koos toorjuustu, keedetud porgandi ja kodujuustuga kohevaks. Haki munavalged noaga hästi väikesteks tükkideks ning sega see eelnevalt vahustatud munasegu hulka. Maitsesta soola ja pipraga ning serveeri röstsaiaga.',
    koostisosad: [9, 14, 18, 23, 29],
    image: 'pildid/munavoie.jpg',
  },
  {
    id: 13,
    recipeName: 'Avokaado-munasalat',
    ingredientsList: [
      '2 küpset avokaadot',
      '4 keedetud muna',
      'pool pikka kurki',
      'hapukoort',
      'soola ja musta pipart',
    ],
    preparationMethod:
      'Võta keedetud mune, küpset avokaadot ja värsket kurki enam-vähem võrdsetes kogustes. Lõika keskmise suurusega kuubikuteks. Sega õrnalt majoneesiga läbi. Soovi korral maitsesta soola-pipraga. Nipid ja soovitused: Laktoosivaba versiooni jaoks kasuta majoneesi või laktoosivaba hapukoort või jogurtit. Kaseiinivaba versiooni jaoks kasuta majoneesi.  LCHF-versiooni jaoks kasuta majoneesi või nt Saare 30% smetana',
    koostisosad: [1, 4, 10, 13, 14],
    image: 'pildid/avomunasalat.jpg',
  },
  {
    id: 14,
    recipeName: 'Täidetud viinerid',
    ingredientsList: [
      '2 kartulit',
      '2 porgandit',
      '2 küüslauguküünt',
      '1 sibul',
      '50 gr riivjuustu',
      '100 gr sulatatud juustu',
      '4 spl riivsaia',
      '2 muna',
      'soola, pipart',
      '0,5 tl kartulimaitseainet',
      '6 pikka viinerit',
      'Õli praadimiseks',
      '1 suvikõrvits',
    ],
    preparationMethod:
      'Koori porgand ja kartul. Riivi jämeda riiviga kartul, porgand ja suvikõrvits. Tükelda sibul ja küüslauk. Kuumuta pannil õli ja lisa pannile riivitud juurviljad, sibul ja küüslauk. Sega korralikult läbi ning hauta kuni juurviljad on peaaegu, et pehmed (veel kergelt krõpmsuvad). Hautamise ajal maitsesta vastavalt enda soovile soola ja pipraga ning lisa kartulimaitseaine. Tõsta pann tulelt ja lase segu nii 10 minutit jahtuda. Sega jahtunud segu sisse munad, riivitud juust, sulatatud juust ning riivsai. Sega sega korralikult läbi. Kui segu on liiga kuum, siis sulab sulatatud juust kiiremini ja segu on liiga vedel. Lõika viinerid keskelt pooleks jättes, siiski viineri mõlemalt poolt otsad lahti lõikamata. Tõsta viiner küpsetuspaberiga kaetud ahjuplaadile ning täida lõigatud vahe juurviljaseguga. Küpseta viinereid eelkuumutatud 180°C ahjus 20 minutit.',
    koostisosad: [6, 8, 11, 14, 18, 22, 24, 27, 31],
    image: 'pildid/viinerid.jpg',
  },
  {
    id: 15,
    recipeName: 'Kartuli-küüslaugupuder',
    ingredientsList: [
      '1 kg kartuleid',
      '5 suurt küüslauguküünt',
      '3 sl võid',
      '2,5 dl sooja piima',
      'soola',
    ],
    preparationMethod:
      'Koori kartulid ning keeda need 1 tl soolaga maitsestatud vees pehmeks. Samal ajal rösti ahjus koorega küüslauguküüned 200 kraadi juures 10 minutit ning seejärel libista pehme sisu koortest välja. Valmis kartulitelt vala keeduvesi ära. Lisa kartulitele röstitud küüslauguküüned, või ja soe piim ning tambi kõik ühtlaseks pudruks. Maitsesta soolaga.',
    koostisosad: [8, 11, 17, 32],
    image: 'pildid/kartulipuder.jpg',
  },
  {
    id: 16,
    recipeName: 'Redise-porgandisupp',
    ingredientsList: [
      '2 kartulit',
      '200 g porgandit',
      '200 g rediseid',
      '1 sibul',
      '1 l köögiviljapuljongit',
      '300 g toorjuustu',
      '2 sl võid',
      '2 sl õli (praadimiseks)',
      'murulauk maitsestamiseks',
    ],
    preparationMethod:
      'Viiluta kõik köögiviljad. Kuumuta potis või ja õli, lisa köögiviljad ning pruunista neid mõni minut. Lisa puljong ning ning keeda keskmisel tulel seni, kuni köögiviljad on kergelt pehmed (jälgi, et need liialt pehmeks ei lähe). Seejärel sega sisse toorjuust ning kuumuta seni, kuni toorjuust on täielikult suppi sulanud.  Raputa supile peale värskeid ürte ning serveeri kohe.',
    koostisosad: [8, 15, 18, 20, 21, 24, 29],
    image: 'pildid/redporsupp.jpg',
  },
];

module.exports = recipes;
